#!/usr/bin/env python3
"""Shared helpers for website publication checks and generation."""

from __future__ import annotations

import html
import re
import unicodedata
from pathlib import Path
from typing import Any

import bibtexparser
import yaml


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "_data"
KNOWLEDGE_DIR = ROOT / "knowledge"

WEBSITE_PUBLICATIONS = DATA_DIR / "publications.yml"
GENERATED_PUBLICATIONS = DATA_DIR / "publications_generated.yml"
OVERRIDES = DATA_DIR / "publication-overrides.yml"
PUBLICATION_PEOPLE = DATA_DIR / "publication-people.yml"
ZOTERO_JSON = KNOWLEDGE_DIR / "library.json"
ZOTERO_BIB = KNOWLEDGE_DIR / "MyLibrary.bib"


DOI_LINK_RE = re.compile(r"https?://(?:dx\.)?doi\.org/([^\"'<>\s]+)", re.I)
TAG_RE = re.compile(r"<[^>]+>")
LATEX_COMMAND_RE = re.compile(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?(?:\{([^{}]*)\})?")
PUNCT_RE = re.compile(r"[^\w\s]+", re.UNICODE)
YEAR_RE = re.compile(r"(19|20)\d{2}")


def load_yaml(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle) or default


def write_yaml(path: Path, data: Any) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# This file is generated by scripts/generate_publications.py.\n")
        handle.write("# Do not edit manually; edit Zotero or _data/publication-overrides.yml.\n")
        yaml.safe_dump(
            data,
            handle,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
        )


def normalize_doi(value: Any) -> str:
    if not value:
        return ""
    doi = str(value).strip()
    doi = re.sub(r"^https?://(?:dx\.)?doi\.org/", "", doi, flags=re.I)
    doi = re.sub(r"^doi:\s*", "", doi, flags=re.I)
    doi = doi.strip().strip(" .;,")
    return doi.lower()


def normalize_title(value: Any) -> str:
    if not value:
        return ""
    text = html.unescape(str(value))
    text = TAG_RE.sub(" ", text)
    text = LATEX_COMMAND_RE.sub(lambda m: m.group(1) or " ", text)
    text = text.replace("{", "").replace("}", "")
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = text.lower()
    text = PUNCT_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def extract_year(value: Any) -> int | None:
    if not value:
        return None
    match = YEAR_RE.search(str(value))
    return int(match.group(0)) if match else None


def item_tags(item: dict[str, Any]) -> set[str]:
    tags = set()
    for tag in item.get("tags") or []:
        if isinstance(tag, dict) and tag.get("tag"):
            tags.add(str(tag["tag"]))
        elif isinstance(tag, str):
            tags.add(tag)
    return tags


def selected_zotero_items() -> list[dict[str, Any]]:
    import json

    with ZOTERO_JSON.open(encoding="utf-8") as handle:
        data = json.load(handle)
    items = data.get("items", data if isinstance(data, list) else [])
    overrides = load_yaml(OVERRIDES, {}) or {}
    excludes = set(overrides.get("exclude_citation_keys") or [])
    selected = []
    for item in items:
        if item.get("itemType") != "journalArticle":
            continue
        if "my-article" not in item_tags(item):
            continue
        if item.get("citationKey") in excludes:
            continue
        selected.append(item)
    return selected


def load_bibtex_articles() -> dict[str, dict[str, Any]]:
    with ZOTERO_BIB.open(encoding="utf-8") as handle:
        db = bibtexparser.load(handle)
    records = {}
    for entry in db.entries:
        keywords = {part.strip() for part in (entry.get("keywords") or "").split(",")}
        if "my-article" not in keywords:
            continue
        if entry.get("ENTRYTYPE", "").lower() != "article":
            continue
        records[entry["ID"]] = entry
    return records


def publication_period(year: int | None) -> str:
    if year is None:
        return "Unknown"
    if year >= 2020:
        return "2020-present"
    if year >= 2014:
        return "2014-2019"
    if year >= 2004:
        return "2004-2013"
    if year >= 1999:
        return "1999-2002"
    return "1994-1996"


def website_entries(path: Path = WEBSITE_PUBLICATIONS) -> list[dict[str, Any]]:
    data = load_yaml(path, {}) or {}
    rows = []
    order = 0
    for period in data.get("periods") or []:
        label = period.get("label")
        for entry_html in period.get("entries_html") or []:
            text = str(entry_html)
            doi_match = DOI_LINK_RE.search(text)
            doi = normalize_doi(doi_match.group(1)) if doi_match else ""
            title_part = text
            if ". " in title_part:
                title_part = title_part.split(". ", 1)[1]
            rows.append(
                {
                    "order": order,
                    "period": label,
                    "entry_html": text,
                    "doi": doi,
                    "title_norm": normalize_title(title_part),
                    "year": extract_year(text),
                }
            )
            order += 1
    return rows


def by_doi(records: list[dict[str, Any]], doi_key: str = "doi") -> dict[str, dict[str, Any]]:
    return {record[doi_key]: record for record in records if record.get(doi_key)}


def item_record(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "citation_key": item.get("citationKey") or item.get("key") or "",
        "year": extract_year(item.get("date")),
        "date": item.get("date") or "",
        "title": item.get("title") or "",
        "title_norm": normalize_title(item.get("title")),
        "journal": item.get("publicationTitle") or item.get("journalAbbreviation") or "",
        "doi": normalize_doi(item.get("DOI")),
        "url": item.get("url") or "",
        "item": item,
    }
